onedr0p/containers

apps/unpackerr/Dockerfile
apps/unpackerr/ci/goss.yaml
apps/unpackerr/ci/latest.sh
apps/unpackerr/entrypoint.sh
apps/unpackerr/metadata.json

Commit generated by whatthecommit.com

Add unpackerr

---

apps/stash/Dockerfile
apps/stash/ci/goss.yaml
apps/stash/ci/latest.sh
apps/stash/entrypoint.sh
apps/stash/metadata.json

Add stashapp/stash

---

apps/kscb/Dockerfile
apps/kscb/backup.sh
apps/kscb/ci/goss.yaml
apps/kscb/ci/latest.sh
apps/kscb/entrypoint.sh
apps/kscb/metadata.json

Adds a kubernetes sidecar backup container

feat: Add kscb

---

apps/postgres-initdb/Dockerfile
apps/postgres-initdb/README.md
apps/postgres-initdb/ci/goss.yaml
apps/postgres-initdb/ci/latest.sh
apps/postgres-initdb/entrypoint.sh
apps/postgres-initdb/metadata.json

feat: add postgres-initdb

---

apps/microbin/Dockerfile
apps/microbin/ci/goss.yaml
apps/microbin/ci/latest.sh
apps/microbin/entrypoint.sh
apps/microbin/metadata.json

This possibly needs some changes from upstream
https://github.com/szabodanika/microbin/issues/46
```
2022-08-09T13:47:42 [INFO] - MicroBin starting on http://0.0.0.0:8080
2022-08-09T13:47:42 [ERROR] - Couldn't create data directory ./pasta_data/public/: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }
thread 'main' panicked at 'Couldn't create data directory ./pasta_data/public/: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/main.rs:70:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ERROR: the container failed to start
INFO: Deleting container
```

feat: add microbin

---

apps/rallly/Dockerfile
apps/rallly/README.md
apps/rallly/ci/goss.yaml
apps/rallly/ci/latest.sh
apps/rallly/metadata.json

https://github.com/lukevella/rallly

add rallly

---

apps/jellyfin/Dockerfile

This matches the version deployed with the official jellyfin container.
Signed-off-by: Nathan Pawelek <nathan@nathanpawelek.com>

feat: Bump to jellyfin-ffmpeg5

---

.github/workflows/action-image-build.yaml

Reverts onedr0p/containers#132

Revert "chore(deps): update docker/build-push-action action to v4"

---

apps/bazarr/Dockerfile

Fixes https://github.com/onedr0p/containers/issues/165

Bazarr: Add py3-psycopg2

---

.github/workflows/action-image-build.yaml

Sorry for the churn on this :-(

Fix stray parantheses

---

apps/lidarr/Dockerfile

This will allow users to add a custom script that can automatically convert formats such as flac -> mp3

feat(lidarr): add ffmpeg support

---

apps/bazarr/Dockerfile
apps/tvheadend/Dockerfile

Reverts onedr0p/containers#217

Revert "chore(deps): update ghcr.io/onedr0p/alpine docker tag to v3.18.2"

---

apps/lidarr/config.xml.tmpl
apps/lidarr/entrypoint.sh
apps/prowlarr/config.xml.tmpl
apps/prowlarr/entrypoint.sh
apps/radarr/config.xml.tmpl
apps/radarr/entrypoint.sh
apps/radarr/zeus/config.xml.tmpl
apps/radarr/zeus/entrypoint.sh
apps/readarr/config.xml.tmpl
apps/readarr/entrypoint.sh
apps/sonarr/config.xml.tmpl
apps/sonarr/develop/config.xml.tmpl
apps/sonarr/develop/entrypoint.sh
apps/sonarr/entrypoint.sh

Configure the arr's themes with env variables :)

feat: arr theme env variables

---

.github/workflows/release-manual.yaml

This unfortunately can only be tested live... if this doesn't work I have some backup plans.

Fix manual release workflow

---

apps/postgres-init/entrypoint.sh

Adjusting entrypoint to allow custom db port

---

apps/home-assistant/Dockerfile
apps/home-assistant/entrypoint.sh
apps/home-assistant/scripts/greeting.sh
apps/home-assistant/scripts/umask.sh

Fixes https://github.com/onedr0p/containers/issues/963

feat(hass): build with upstream python 3.12-alpine

---

apps/bazarr/entrypoint.sh
apps/lidarr/entrypoint.sh
apps/prowlarr/entrypoint.sh
apps/radarr/entrypoint.sh
apps/readarr/entrypoint.sh
apps/sabnzbd/entrypoint.sh
apps/sonarr/entrypoint.sh

Fixes https://github.com/onedr0p/containers/issues/1010

fix: add mkdir config for certain containers

---

apps/home-assistant/entrypoint.sh

See https://hacs.xyz/docs/setup/download/

fix(home-assistant): update HACS install url

---

.github/workflows/check-issue.yaml

Please squash this when merging.

FEAT: Automatic close on unsupported platform

---

apps/qbittorrent/Dockerfile

Trying to address memory issues and seeing if this works

fix: qbittorrent swap to qt5 builds

---

apps/qbittorrent/Dockerfile

Reverts onedr0p/containers#1077
qt5 had no impact on my memory issues

Revert "fix: qbittorrent swap to qt5 builds"

---

apps/volsync/Dockerfile
apps/volsync/README.md
apps/volsync/ci/goss.yaml
apps/volsync/ci/latest.sh
apps/volsync/metadata.yaml

Reverts onedr0p/containers#1143

Revert "Delete apps/volsync directory"
