onedr0p/containers

- apps/alpine/Dockerfile
- apps/ubuntu/Dockerfile
> fix: Strip debugging information from envsubt binary on base images

- apps/postgres-initdb/entrypoint.sh
Some containers (e.g. teslamate) require additional privileges like super-user. This allows the create user flags to be specified.
> Allow flags to be specified for postgres user

- apps/alpine/ci/latest.sh
- apps/ubuntu/ci/latest.sh
v1 of the registry API intermitently fails with a 410 gone error
This moves the latest scripts to use v2 of the API
I've updated them to use some search terms as well to limit the results
> Move base images to v2 of registry API for latest check

- apps/alpine/Dockerfile
- apps/emby/Dockerfile
- apps/jellyfin/Dockerfile
- apps/lidarr/Dockerfile
- apps/plex/Dockerfile
- apps/plex/amd/Dockerfile
- apps/prowlarr/Dockerfile
- apps/radarr/Dockerfile
- apps/radarr/zeus/Dockerfile
- apps/readarr/Dockerfile
- apps/sabnzbd/entrypoint.sh
- apps/sonarr/Dockerfile
- apps/sonarr/develop/Dockerfile
The Dockerfile RUN to add the umask to /etc/bash.bashrc was not including a newline so that subsequent appendings to the same file would cause an error.  Conducted an audit of the repository for various similar uses of printf and added newlines where it seemed to make sense.
Notable exceptions:
- apps/*/ci/latest.sh
- apps/*/scripts/sleep.sh
Signed-off-by: Dan Christensen <opello@opello.org>
> fix: Add newlines to various printf format strings

- .github/workflows/release-manual.yaml
- .github/workflows/release-schedule.yaml
I propose to add concurrency to release builds.
It will allow to have action running every hour without spawning gremlins ;)
The next action will get into queue and will wait for previous execution to finish.
I use this successfully in my long running github actions.
> Add concurrency to workflows to avoid multiple release builds

- apps/prowlarr/metadata.json
Now that Prowlarr has stable releases, they should be built. 😄
> Build containers for Prowlarr stable releases.

- apps/postgres-init/entrypoint.sh
This allows the intended app user's password to be rotated by the admin using the initContainer rather than manually using `psql`.
> feat(postgres-init): ALTER ROLE every script run

- .github/workflows/action-image-build.yaml
Two discovered bugs from the first scheduled run:
- digest upload appears to have regressed after my tests? should be fixed
- need to test if images need to be built. I'd removed this while I was testing, just added it back.
> quick follow-up fixes for matrixed builds

- .github/workflows/action-image-build.yaml
Per Title. I'd apparently accidentally removed the cue validation step :-/
Since the metadata is important to generate the matrices now, I put Cue into the Prepare step. It's tough to fully test github actions, but I was able to run the validation command locally (captured below).
Failed Validation:
```bash
~/onedr0p-containers ❯❯❯ find ./apps/ -name metadata.json | xargs -I {} cue vet --schema '#Spec' {} ./metadata.rules.cue
channels.0.asdf: field not allowed:
./apps/emby/metadata.json:16:7
./metadata.rules.cue:1:8
./metadata.rules.cue:4:13
./metadata.rules.cue:4:16
./metadata.rules.cue:7:12
~/onedr0p-containers ❯❯❯ echo $?
123
```
Successful Validation:
```bash
~/onedr0p-containers ❯❯❯ find ./apps/ -name metadata.json | xargs -I {} cue vet --schema '#Spec' {} ./metadata.rules.cue …
```
> Restore Cue Validation

- .github/workflows/action-image-build.yaml
(Merge Cue PR first)
outcome is "failure" not "failed" when a step fails. Without this fix, Goss failures will fail the amd64 build, but will not set the failed bit, leading to containers that only have arm64 builds attached
> Failed bit

- .github/workflows/action-image-build.yaml
Quick hotfix to ensure the failed bit gets checked. This is obviously still a bit brittle, I'll spend some time today looking for a more robust way to do this.
> fix(ci): Ensure failed bit gets uploaded

- .github/scripts/prepare-images.py
- .github/workflows/action-image-build.yaml
This PR should be a bit more permanent fix to failure checking. No instead of counting on the upload of a "failed" file we test for, instead we just compare the count of platforms to the count of digests, and if they don't match, we bail.
As always, there isn't really a good way for me to test this pre-merge, so please look carefully :-D We can run a manual release after merge to test it.
> Test platform count rather than failed bit

- .github/workflows/action-image-build.yaml
Per title. `toJSON` pretty prints for some reason, which makes every script harder. use `cat << EOF` to fix.
> fix(ci): EXPECTED_COUNT length check

- apps/lidarr/metadata.json
This allows building of the `plugins` branch which is useful for developing and adding plugins to Lidarr. Considering that this branch has yet to make it to main and may or may not get merged anytime soon, i have opted to leave it designated as unstable.
thanks!
> (lidarr): add plugins branch container

- .github/workflows/release-manual.yaml
I thought I had already done this -- Scheduled Release already allows most of these inputs. This PR makes these workflows roughly identical, with the added option to select channels.
> Set Manual Release to use same pattern as Scheduled Release

- apps/transmission/Dockerfile
This should fix #911 - adds the gnu version of `find` which appears to be required by transmission's default `post-process.sh` script.
fixes #911
> [#911] fix: add `findutils` to transmission image.

- .github/workflows/release-scheduled.yaml
Since a few days the scheduled release is not working as intended, the build image job should be called with a new permission.
> fix: release-scheduled permissions

- apps/sonarr/Dockerfile
The updated download url was retrieved from https://github.com/linuxserver/docker-sonarr/commit/d2691783223ccffd027ee7f37808f90ce8fb83e8
> fix: update sonarr download url

- apps/home-assistant/Dockerfile
Encountered an issue over here when attempting to install the shapely dependency from the Linuxserver wheels (2.0.2 wheel is not there) https://github.com/mampfes/hacs_waste_collection_schedule/issues/1705
[ReneNulschDE](https://github.com/ReneNulschDE) is suggesting to use the HA source "https://wheels.home-assistant.io/musllinux/" which is used by the HA-base image here https://github.com/home-assistant/docker-base/blob/b9743b86993c554b6229f5866202717860d79d7a/alpine/rootfs/etc/pip.conf#L3
So far so good 🤞
> Use HA wheels

- apps/postgres-init/entrypoint.sh
Initialize the new database using SQL statements from the file `initdb/${dbname}.sql` which can be mounted from configMap. For example to initialize PostGIS or TimescaleDB extensions.
> Adjusting entrypoint to allow database initialization

- apps/bazarr/Dockerfile
If you're currently analyzing track language, missing mediainfo will cause rescan tasks to hang indefinitely, preventing an update or sync of the backends. This appears to have been removed in the 1.4.2 release.
> Add mediainfo back to image

- apps/postgres-init/entrypoint.sh
The used syntax tries to call a non-existent `database_init_file` command:
```
Update password for user <user> ...
ALTER ROLE
Create Database <database> ...
/entrypoint.sh: line 59: database_init_file: command not found
Update User Privileges on Database ...
GRANT
```
> Fix shell syntax for parameter

- apps/bazarr/Dockerfile
- apps/bazarr/entrypoint.sh
Updates to python 3.12
Updates to py requirements
Updates to bin location, now `/app/bin` instead of `/app`
> fix(bazarr): can haz python 3.12?

- apps/sabnzbd/Dockerfile
This will deprecated building a container image just for par2
> fix(sabnzbd): extract par2 turbo from lsio container

- .github/scripts/templates/README.md.j2
- apps/bazarr/Dockerfile
- apps/bazarr/entrypoint.sh
- apps/home-assistant/Dockerfile
- apps/home-assistant/entrypoint.sh
- apps/jbops/Dockerfile
- apps/jbops/entrypoint.sh
- apps/plex/Dockerfile
- apps/plex/entrypoint.sh
- apps/postgres-init/Dockerfile
- apps/prowlarr/Dockerfile
- apps/prowlarr/entrypoint.sh
- apps/qbittorrent/Dockerfile
- apps/radarr/Dockerfile
- apps/radarr/entrypoint.sh
- apps/sabnzbd/Dockerfile
- apps/sabnzbd/entrypoint.sh
- apps/sonarr/Dockerfile
- apps/sonarr/entrypoint.sh
- apps/tautulli/Dockerfile
- apps/tautulli/README.md
- apps/tautulli/entrypoint.sh
- add `entrypoint.sh` script to `ENTRYPOINT`
- update Dockerfile ENVs
> refactor(entrypoint): add entrypoint script to ENTRYPOINT

- apps/qbittorrent/Dockerfile
qBittorrent relies on python to run search plugins.
> feat: install python3 in qbittorrent

- scripts/render-readme.py
render-readme.py was creating links that lead to a 404, this should fix the issue.
> Fix HTML link in render-readme.py

- apps/prowlarr/Dockerfile
- apps/radarr/Dockerfile
- apps/sonarr/Dockerfile
.net 6 onwards, DOTNET_ is preferred over COMPlus_ https://github.com/dotnet/runtime/commit/fbdcec9060f46353761ac8ee14d11d6206049395 it first uses DOTNET_, and then COMPlus_ as a legacy fallback.
This form is documented here: [dotnet/runtime@1fa1745/docs/workflow/debugging/coreclr/debugging-runtime.md#disabling-managed-attachdebugging](https://github.com/dotnet/runtime/blob/1fa1745581e26069093a679626e346b675aa534f/docs/workflow/debugging/coreclr/debugging-runtime.md#disabling-managed-attachdebugging). COMPlus_ is used as a legacy fallback (naming convention of environment variables should use namespace and COMPlus was some legacy name they stopped using a while back).
> fix: use `DOTNET_EnableDiagnostics`
